const clues = [
    "\"MOM I’M IN CLASS\" (parent interrupts)",
    "\"Oh shoot let me start the recording\"",
    "Shirtless Guy (or girl)",
    "“Raise your hand...”",
    "Prof calls on someone who didn’t raise their hand",
    "Forgets to record lecture",
    "Prof mutes themself and someone has to remind them",
    "\"Can you see this?\" (you can’t see it)",
    "Someone dings in > 10 min late",
    "Coronavirus Joke",
    "\"Stay Healthy\", \"Hope everyone’s healthy\", etc.",
    "Someone falls asleep",
    "Prof accidentally leaves call",
    "Someone typing, possibly with a hammer",
    "Embarrassing Background",
    "Someone clearly has Corona (coughing fit)",
    "\"Can everyone go on mute?\"",
    "Guest Lecturer 2.0",
    "Prof requires a basic technology tutorial",
    "Student requires a basic technology tutorial",
    "Prof complains about online format",
    "\"You’re still sharing your screen\"",
    "Pajamas",
    "Prof Catches Corona",
    "Someone can't figure out how to put their hand down",
    "Person raises physical hand instead of Zoom hand",
    "Prof ignores someone with their hand up",
    "Someone gets up and leaves while their video is on",
    "Prof gets distracted by something in someone's video",
    "Student shows off their pet/child",
    "Someone mentions a timezone",
    "Someone is eating"
];

export default clues
